update plugin to adopt specificaiton 0.3.1
yunify/hostnic-cni pull request #3
Opened 2017-05-15 03:13 UTC by martinyunify

update plugin to adopt specificaiton 0.3.1

2017-05-16 12:36 UTC, jolestar commented
以后对 vendor 的变更单独提交一下，不然 review 的时候 diff 加载困难。

2017-05-16 12:37 UTC, jolestar requested changes

2017-05-16 12:37 UTC, jolestar commented on README.md
> -    "providerConfigFile":"/etc/qingcloud/client.yaml",
这个弄到一个文件里感觉不好
1. 这个是可以省略的，sdk 有默认价值 配置文件的路径。以后还有通过 metaserver 自动加载 key 的机制。
2. 有关 client 相关的配置不需要污染 hostnic 的配置，比如开启 client 的 debug 模式。

2017-05-19 09:54 UTC, martinyunify commented on README.md
> -    "providerConfigFile":"/etc/qingcloud/client.yaml",
已经改回来了。

2017-05-19 10:07 UTC, jolestar approved these changes

2017-05-19 10:08 UTC, jolestar commented
这个一个版本可以先这样做，但如果是多个 vxnet，让用户自己通过配置文件设置 route，会比较麻烦，这个可以考虑在 hostcni 里自动实现。

2017-05-19 10:08 UTC, merged